import { PGlite } from "@electric-sql/pglite";
import fs from "fs";
const db = new PGlite();
const schema = fs.readFileSync(new URL("../supabase/schema.sql", import.meta.url), "utf8");
await db.exec(`
 create role anon; create role authenticated;
 create schema auth;
 create table auth.users (id uuid primary key default gen_random_uuid(), email text, raw_user_meta_data jsonb default '{}');
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.uid', true), '')::uuid $$;
 create publication supabase_realtime;
`);
await db.exec(schema);
await db.exec(schema); // idempotente
let ok = 0, ko = 0;
const t = (name, cond) => { cond ? ok++ : ko++; console.log(cond ? "OK " : "KO ", name); };
const as = async (uid, role, sql) => { await db.exec(`set role ${role}; select set_config('request.uid','${uid ?? ""}',false)`); try { return await db.query(sql); } finally { await db.exec("reset role"); } };
const fails = async (uid, role, sql) => { try { await as(uid, role, sql); return false; } catch { return true; } };

const u1 = (await db.query("insert into auth.users (email) values ('a@x.it') returning id")).rows[0].id;
const u2 = (await db.query("insert into auth.users (email) values ('b@x.it') returning id")).rows[0].id;
const roles = (await db.query("select id, role from profiles order by created_at")).rows;
t("primo utente = titolare", roles.find(r => r.id === u1).role === "titolare");
t("secondo utente = tecnico", roles.find(r => r.id === u2).role === "tecnico");
t("tecnico non si promuove", await fails(u2, "authenticated", `update profiles set role='titolare' where id='${u2}'`));
t("tecnico non usa Sara", await fails(u2, "authenticated", `select sara_register_request('intervento','Mario Rossi','338','','via Roma','guasto','normale','','sereno',null,null,'')`));
t("anon non legge clienti", await fails(null, "anon", "select * from clients"));
const reg = (await as(u1, "authenticated", `select * from sara_register_request('urgenza','Mario Rossi','338 123 4567','','via Roma 1','allagamento','urgente','','preoccupato',null,null,'prop')`)).rows[0];
t("richiesta in attesa", reg.status === "in_attesa");
t("nessuna scrittura diretta su sara_requests", await fails(u1, "authenticated", `update sara_requests set status='confermata' where id='${reg.id}'`));
t("senza nome rifiuta", await fails(u1, "authenticated", `select sara_register_request('intervento','','1','','','x','normale','','sereno',null,null,'')`));
t("nulla creato prima della conferma", (await db.query("select count(*)::int c from interventions")).rows[0].c === 0);
const conf = (await as(u1, "authenticated", `select * from sara_confirm_request('${reg.id}')`)).rows[0];
t("confermata", conf.status === "confermata" && conf.intervention_id);
const iv = (await db.query("select * from interventions")).rows[0];
t("intervento critico con numero", iv.priority === "critica" && /^INT-\d{4}-00001$/.test(iv.number));
t("cliente creato", (await db.query("select count(*)::int c from clients")).rows[0].c === 1);
t("non si decide due volte", await fails(u1, "authenticated", `select sara_confirm_request('${reg.id}')`));
const reg2 = (await as(u1, "authenticated", `select * from sara_register_request('intervento','Mario Rossi','3381234567','','via Roma 1','altro guasto','normale','','sereno',null,null,'')`)).rows[0];
await as(u1, "authenticated", `select sara_confirm_request('${reg2.id}')`);
t("cliente abituale riconosciuto (stesso telefono)", (await db.query("select count(*)::int c from clients")).rows[0].c === 1);
const reg3 = (await as(u1, "authenticated", `select * from sara_register_request('preventivo','Anna Bianchi','339','','','quanto costa','normale','','sereno',null,null,'')`)).rows[0];
await as(u1, "authenticated", `select sara_reject_request('${reg3.id}')`);
t("rifiutata non crea niente", (await db.query("select count(*)::int c from interventions")).rows[0].c === 2 && (await db.query("select count(*)::int c from clients")).rows[0].c === 1);
const rem = (await as(u1, "authenticated", `select * from sara_register_request('promemoria','','','','','chiamare il fornitore','normale','','sereno',now(),null,'')`)).rows[0];
t("promemoria già confermato", rem.status === "confermata");
t("tecnico non vede richieste", (await as(u2, "authenticated", "select * from sara_requests")).rows.length === 0);
t("tecnico non vede interventi non suoi", (await as(u2, "authenticated", "select * from interventions")).rows.length === 0);
await db.query(`update interventions set technician_id='${u2}' where id='${iv.id}'`);
t("tecnico vede il proprio intervento e il cliente", (await as(u2, "authenticated", "select * from interventions")).rows.length === 1 && (await as(u2, "authenticated", "select * from clients")).rows.length === 1);
t("tecnico non scrive clienti", await fails(u2, "authenticated", `insert into clients (name) values ('x')`));
t("solo titolare modifica il listino", await fails(u2, "authenticated", `select sara_save_price('x','a',1,null)`));
const price = (await as(u1, "authenticated", `select * from sara_save_price('Uscita','Caldaia, boiler',60,null)`)).rows[0];
t("listino salvato con parole chiave", price.keywords.join() === "boiler,caldaia");

// ---- Preventivi ----
const regQ = (await as(u1, "authenticated", `select * from sara_register_request('preventivo','Giulia Neri','339 555 0123','','Via Pellicceria 4','sostituzione caldaia','normale','','sereno',null,60,'prop')`)).rows[0];
const confQ = (await as(u1, "authenticated", `select * from sara_confirm_request('${regQ.id}')`)).rows[0];
t("conferma di un preventivo crea cliente e bozza", confQ.quote_id && !confQ.intervention_id);
const quote = (await db.query(`select * from quotes where id='${confQ.quote_id}'`)).rows[0];
t("bozza con numero progressivo", quote.status === "bozza" && /^PRV-\d{4}-00001$/.test(quote.number));
const qi = (await db.query(`select * from quote_items where quote_id='${quote.id}'`)).rows;
t("prima voce dal listino", qi.length === 1 && Number(qi[0].unit_price) === 60);
t("tecnico non vede i preventivi", (await as(u2, "authenticated", "select * from quotes")).rows.length === 0);
t("tecnico non crea preventivi", await fails(u2, "authenticated", `insert into quotes (number, client_id, title) values ('', '${quote.client_id}', 'x')`));
t("bozza modificabile", !(await fails(u1, "authenticated", `insert into quote_items (quote_id, description, quantity, unit_price) values ('${quote.id}', 'manodopera', 2, 35)`)));
t("non si salta da bozza ad accettato", await fails(u1, "authenticated", `update quotes set status='accettato' where id='${quote.id}'`));
await as(u1, "authenticated", `update quotes set status='inviato' where id='${quote.id}'`);
t("inviato: voci bloccate", await fails(u1, "authenticated", `update quote_items set unit_price=1 where quote_id='${quote.id}'`));
t("inviato: titolo bloccato", await fails(u1, "authenticated", `update quotes set title='altro' where id='${quote.id}'`));
t("inviato: non si elimina", await fails(u1, "authenticated", `delete from quotes where id='${quote.id}'`));
await as(u1, "authenticated", `update quotes set status='accettato' where id='${quote.id}'`);
t("accettato e' definitivo", await fails(u1, "authenticated", `update quotes set status='rifiutato' where id='${quote.id}'`));
const q2 = (await as(u1, "authenticated", `insert into quotes (number, client_id, title) values ('', '${quote.client_id}', 'bozza da eliminare') returning *`)).rows[0];
await as(u1, "authenticated", `insert into quote_items (quote_id, description, quantity, unit_price) values ('${q2.id}', 'x', 1, 1)`);
await as(u1, "authenticated", `delete from quotes where id='${q2.id}'`);
t("una bozza si elimina con le sue voci", (await db.query(`select count(*)::int c from quote_items where quote_id='${q2.id}'`)).rows[0].c === 0);

// ---- Fatture ----
const clientId = quote.client_id;
t("nessuna scrittura diretta su fatture", await fails(u1, "authenticated", `insert into invoices (number, client_id, title, due_date) values ('X', '${clientId}', 'x', current_date)`));
t("tecnico non emette fatture", await fails(u2, "authenticated", `select create_invoice('${clientId}','x','',null,'[{"description":"a","quantity":1,"unit_price":10,"vat_rate":22}]')`));
const inv1 = (await as(u1, "authenticated", `select * from create_invoice('${clientId}','Lavoro di prova','',null,'[{"description":"manodopera","quantity":2,"unit_price":35,"vat_rate":22},{"description":"ricambio","quantity":1,"unit_price":10.5,"vat_rate":22}]')`)).rows[0];
t("prima fattura con numero progressivo", /^FAT-\d{4}-00001$/.test(inv1.number) && inv1.status === "in_attesa");
t("scadenza a 30 giorni se non indicata", (await db.query(`select (due_date - issue_date) d from invoices where id='${inv1.id}'`)).rows[0].d === 30);
t("voci salvate", (await db.query(`select count(*)::int c from invoice_items where invoice_id='${inv1.id}'`)).rows[0].c === 2);
t("senza voci non si emette", await fails(u1, "authenticated", `select create_invoice('${clientId}','x','',null,'[]')`));
t("voce non valida: niente fattura a meta'", await fails(u1, "authenticated", `select create_invoice('${clientId}','x','',null,'[{"description":"a","quantity":0,"unit_price":10}]')`));
t("scadenza nel passato rifiutata", await fails(u1, "authenticated", `select create_invoice('${clientId}','x','',current_date - 1,'[{"description":"a","quantity":1,"unit_price":10}]')`));
const inv2 = (await as(u1, "authenticated", `select * from create_invoice_from_quote('${quote.id}', null)`)).rows[0];
t("numerazione SENZA BUCHI anche dopo errori", /-00002$/.test(inv2.number));
t("fattura dal preventivo: stesse voci e collegamento", inv2.quote_id === quote.id && (await db.query(`select count(*)::int c from invoice_items where invoice_id='${inv2.id}'`)).rows[0].c === 2);
t("lo stesso preventivo non si fattura due volte", await fails(u1, "authenticated", `select create_invoice_from_quote('${quote.id}', null)`));
const q3 = (await as(u1, "authenticated", `insert into quotes (number, client_id, title) values ('', '${clientId}', 'non accettato') returning *`)).rows[0];
t("preventivo non accettato non si fattura", await fails(u1, "authenticated", `select create_invoice_from_quote('${q3.id}', null)`));
t("tecnico non vede le fatture", (await as(u2, "authenticated", "select * from invoices")).rows.length === 0);
const paid = (await as(u1, "authenticated", `select * from mark_invoice_paid('${inv1.id}', 'bonifico')`)).rows[0];
t("pagata con data e metodo", paid.status === "pagata" && paid.paid_at && paid.payment_method === "bonifico");
t("una pagata non si annulla ne' si ripaga", (await fails(u1, "authenticated", `select cancel_invoice('${inv1.id}','x')`)) && (await fails(u1, "authenticated", `select mark_invoice_paid('${inv1.id}', null)`)));
const canc = (await as(u1, "authenticated", `select * from cancel_invoice('${inv2.id}','errore di importo')`)).rows[0];
t("annullata con motivo", canc.status === "annullata" && canc.cancel_reason === "errore di importo");
const inv3 = (await as(u1, "authenticated", `select * from create_invoice_from_quote('${quote.id}', null)`)).rows[0];
t("dopo l'annullamento il preventivo si puo' rifatturare (numero successivo)", /-00003$/.test(inv3.number));
t("le voci di una fattura non si modificano", await fails(u1, "authenticated", `update invoice_items set unit_price = 1 where invoice_id='${inv1.id}'`));
t("una fattura non si elimina", await fails(u1, "authenticated", `delete from invoices where id='${inv1.id}'`));
console.log(`\n${ok} ok, ${ko} falliti`); process.exit(ko ? 1 : 0);
