import { PGlite } from "@electric-sql/pglite";
import fs from "fs";
const db = new PGlite();
const schema = fs.readFileSync(new URL("../supabase/schema.sql", import.meta.url), "utf8");
await db.exec(`
 create role anon; create role authenticated;
 create schema auth;
 create table auth.users (id uuid primary key default gen_random_uuid(), email text, raw_user_meta_data jsonb default '{}');
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.uid', true), '')::uuid $$;
 create publication supabase_realtime;
`);
await db.exec(schema);
await db.exec(schema); // idempotente
let ok = 0, ko = 0;
const t = (name, cond) => { cond ? ok++ : ko++; console.log(cond ? "OK " : "KO ", name); };
const as = async (uid, role, sql) => { await db.exec(`set role ${role}; select set_config('request.uid','${uid ?? ""}',false)`); try { return await db.query(sql); } finally { await db.exec("reset role"); } };
const fails = async (uid, role, sql) => { try { await as(uid, role, sql); return false; } catch { return true; } };

const u1 = (await db.query("insert into auth.users (email) values ('a@x.it') returning id")).rows[0].id;
const u2 = (await db.query("insert into auth.users (email) values ('b@x.it') returning id")).rows[0].id;
const roles = (await db.query("select id, role from profiles order by created_at")).rows;
t("primo utente = titolare", roles.find(r => r.id === u1).role === "titolare");
t("secondo utente = tecnico", roles.find(r => r.id === u2).role === "tecnico");
t("tecnico non si promuove", await fails(u2, "authenticated", `update profiles set role='titolare' where id='${u2}'`));
t("tecnico non usa Sara", await fails(u2, "authenticated", `select sara_register_request('intervento','Mario Rossi','338','','via Roma','guasto','normale','','sereno',null,null,'')`));
t("anon non legge clienti", await fails(null, "anon", "select * from clients"));
const reg = (await as(u1, "authenticated", `select * from sara_register_request('urgenza','Mario Rossi','338 123 4567','','via Roma 1','allagamento','urgente','','preoccupato',null,null,'prop')`)).rows[0];
t("richiesta in attesa", reg.status === "in_attesa");
t("nessuna scrittura diretta su sara_requests", await fails(u1, "authenticated", `update sara_requests set status='confermata' where id='${reg.id}'`));
t("senza nome rifiuta", await fails(u1, "authenticated", `select sara_register_request('intervento','','1','','','x','normale','','sereno',null,null,'')`));
t("nulla creato prima della conferma", (await db.query("select count(*)::int c from interventions")).rows[0].c === 0);
const conf = (await as(u1, "authenticated", `select * from sara_confirm_request('${reg.id}')`)).rows[0];
t("confermata", conf.status === "confermata" && conf.intervention_id);
const iv = (await db.query("select * from interventions")).rows[0];
t("intervento critico con numero", iv.priority === "critica" && /^INT-\d{4}-00001$/.test(iv.number));
t("cliente creato", (await db.query("select count(*)::int c from clients")).rows[0].c === 1);
t("non si decide due volte", await fails(u1, "authenticated", `select sara_confirm_request('${reg.id}')`));
const reg2 = (await as(u1, "authenticated", `select * from sara_register_request('intervento','Mario Rossi','3381234567','','via Roma 1','altro guasto','normale','','sereno',null,null,'')`)).rows[0];
await as(u1, "authenticated", `select sara_confirm_request('${reg2.id}')`);
t("cliente abituale riconosciuto (stesso telefono)", (await db.query("select count(*)::int c from clients")).rows[0].c === 1);
const reg3 = (await as(u1, "authenticated", `select * from sara_register_request('preventivo','Anna Bianchi','339','','','quanto costa','normale','','sereno',null,null,'')`)).rows[0];
await as(u1, "authenticated", `select sara_reject_request('${reg3.id}')`);
t("rifiutata non crea niente", (await db.query("select count(*)::int c from interventions")).rows[0].c === 2 && (await db.query("select count(*)::int c from clients")).rows[0].c === 1);
const rem = (await as(u1, "authenticated", `select * from sara_register_request('promemoria','','','','','chiamare il fornitore','normale','','sereno',now(),null,'')`)).rows[0];
t("promemoria già confermato", rem.status === "confermata");
t("tecnico non vede richieste", (await as(u2, "authenticated", "select * from sara_requests")).rows.length === 0);
t("tecnico non vede interventi non suoi", (await as(u2, "authenticated", "select * from interventions")).rows.length === 0);
await db.query(`update interventions set technician_id='${u2}' where id='${iv.id}'`);
t("tecnico vede il proprio intervento e il cliente", (await as(u2, "authenticated", "select * from interventions")).rows.length === 1 && (await as(u2, "authenticated", "select * from clients")).rows.length === 1);
t("tecnico non scrive clienti", await fails(u2, "authenticated", `insert into clients (name) values ('x')`));
t("solo titolare modifica il listino", await fails(u2, "authenticated", `select sara_save_price('x','a',1,null)`));
const price = (await as(u1, "authenticated", `select * from sara_save_price('Uscita','Caldaia, boiler',60,null)`)).rows[0];
t("listino salvato con parole chiave", price.keywords.join() === "boiler,caldaia");
console.log(`\n${ok} ok, ${ko} falliti`); process.exit(ko ? 1 : 0);
